# Sólo las rutas de la parte de administración de las ponencias
admin_ponencia_list:
    pattern:  /list
    defaults: { _controller: DesymfonyBundle:AdminPonencia:list }

admin_ponencia_new:
    pattern:  /new
    defaults: { _controller: DesymfonyBundle:AdminPonencia:new }

admin_ponencia_edit:
    pattern:  /edit/{id}
    defaults: { _controller: DesymfonyBundle:AdminPonencia:edit }

admin_ponencia_delete:
    pattern:  /delete/{id}
    defaults: { _controller: DesymfonyBundle:AdminPonencia:delete }

admin_ponencia_apuntados:
    pattern:  /show/{id}
    defaults: { _controller: DesymfonyBundle:AdminPonencia:show }

