ponencias:
    pattern:  /ponencias.{_format}
    defaults: { _controller: DesymfonyBundle:Ponencia:index, _format: html }
    requirements:
      _format: html|xml|ics

ponencia:
    pattern:  /ponencia/{slug}
    defaults: { _controller: DesymfonyBundle:Ponencia:ponencia }

apuntarse:
    pattern:  /me-apunto-a-{slug}
    defaults: { _controller: DesymfonyBundle:Ponencia:apuntarse }
