registro:
    pattern:  /registro
    defaults: { _controller: DesymfonyBundle:Usuario:registro }

perfil:
    pattern:  /perfil
    defaults: { _controller: DesymfonyBundle:Usuario:perfil }

login:
    pattern:  /login
    defaults: { _controller: DesymfonyBundle:Usuario:login }

login_check:
    pattern: /perfil/check

logoff:
    pattern:  /perfil/logoff
    defaults: { _controller: DesymfonyBundle:Usuario:logoff }
